version: '3'
services:
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=pass
  app:
    image: nodejs-starter:latest
    environment:
      - MONGODB_URI=mongodb://app:pass@mongodb
    build: 
      context: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongodb